[basic_info]
annotation_file_path = 'datasets/low_mid_level_vision/contour_completion/annotation.csv'
match_factors = ['SampleId', 'TopShape']
#filter_factor_level = { Type = "linearity"}
factor_variable = "Type"
reference_level = "no_occlusion"

[options]
pretraining = "ImageNet"

[saving_folders]
results_folder = "results/similarity_judgments/contour_completion"

[transformation.values]
translation = false
scale = false
rotation = false
rotation = false
