[basic_info]
annotation_file_path = 'datasets/low_mid_level_vision/decomposition/annotation.csv'
match_factors = ['PairShapeId']
filter_factor_level = { ShapeType = "unfamiliar" }
factor_variable = "SplitType"
reference_level = "no_split"

[options]
pretraining = "ImageNet"

[saving_folders]
results_folder = "results/examples/decomposition/familiar"

[transformation]
fill_color = [0, 0, 0]
matching_transform = true
repetitions = 50

[transformation.values]
translation_X = [-0.2, 0.2]
translation_Y = [-0.2, 0.2]
scale = [0.8, 1.2]
rotation = [0, 360]
