[basic_info]
annotation_file_path = 'data/low_mid_level_vision/NAP_vs_MP_3D_geons_standard/annotation.csv'
match_factors = ["SampleName"]
factor_variable = "Type"
reference_level = "reference"

[options]
pretraining = "ImageNet"

[saving_folders]
results_folder = "results/similarity_judgments/NAPvsMP_3D_geons_standard"

[transformation]
fill_color = [0, 0, 0]
matching_transform = true
repetitions = 50

[transformation.values]
translation_X = [-0.2, 0.2]
translation_Y = [-0.2, 0.2]
scale = [0.8, 1.2]
rotation = [-50, 50]
