[basic_info]
annotation_file_path = 'datasets/visual_illusions/thatcher_illusion/annotation.csv'
match_factors = ["FaceId"]
factor_variable = "Transformation"
reference_level = "normal"

[options]
pretraining = "ImageNet"

[saving_folders]
results_folder = "results/similarity_judgment/thatcher_illusion"


[transformation]
fill_color = [0, 0, 0]
matching_transform = true
repetitions = 50

[transformation.values]
translation_X = [-0.2, 0.2]
translation_Y = [-0.2, 0.2]
scale = [0.8, 1.2]
rotation = [-50, 50]
